# Deliverable 1. Retrieve Weather Data.
---
1. Create a folder called `Weather_Database` to save all the files related with this deliverable.

2. Save the `Weather_Database_starter_code.ipynb` starter code to the `Weather_Database` folder and rename it as `Weather_Database.ipynb`.

3. Use the `np.random.uniform` function to generate a new set of 2,000 random latitudes and 2,000 longitudes.

4. Use the `citipy` module to get the nearest city for each latitude and longitude combination.

5. Import your OpenWeatherMap's API key and assemble the API call URL as a string variable. Recall to edit the `config.py` file to add your API key; also, it's critical to avoid publishing your API key on your GitHub repository.

6. Retrieve the following information from the API call:

    * Latitude and longitude

    * Maximum temperature

    * Percent humidity

    * Percent cloudiness

    * Wind speed

    * Weather description (for example, clouds, fog, light rain, clear sky)

7. Add the weather data to a new DataFrame.

8. Export the DataFrame as a CSV file, and save it as `WeatherPy_Database.csv` in the `Weather_Database` folder.
---

In [2]:
# Import initial libraries
import numpy as np
import pandas as pd
from citipy import citipy

## Use the `np.random.uniform` function to generate a new set of 2,000 random latitudes and 2,000 longitudes.

In [3]:
# Create a set of random latitude and longitude combinations
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)

# Use the zip function to create an iterator of tuples containing the latitude and longitude combinations
lat_lngs = zip(lats, lngs)

In [4]:
# Add the latitudes and longitudes to a list
coordinates = list(lat_lngs)

## Use the `citipy` module to get the nearest city for each latitude and longitude combination.

In [5]:
# Create an empty list for holding the cities
cities = []

# Use a for loop to identify nearest city for each latitude and longitude combination using the citipy module
for coordinate in coordinates:
    # Use the citipy module to identify the nearest city to the current coordinate
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

744

## Import your OpenWeatherMap's API key and assemble the API call URL as a string variable. Recall to edit the `config.py` file to add your API key.

In [9]:
#Import dependencies
from citipy import citipy
import requests
from config import weather_api_key
from datetime import datetime

In [11]:
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key

## Retrieve the following information from the API call.

- The latitude and longitude
- The Max temperature
- The % humidity
- The % cloudiness
- The Wind speed
- The Weather description, i.e., cloudy, fog, light rain, clear sky, etc.

In [12]:
# Create an empty list to hold weather data for each city
city_data = []

# Print a message to indicate that the data retrieval starts
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters and set them to 1
record_count = 1
set_count = 1

# Loop through all the cities in our list to fetch weather data for each city
for i, city in enumerate(cities):
        
    # Group cities in sets of 50 for logging purposes
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create an endpoint URL for each city
    city_url = url + "&q=" + city.replace(" ","+")
    
    # Log the url, record, and set numbers
    print(f"Processing Record {record_count} of Set {set_count} | {city}")

    # Add 1 to the record count
    record_count += 1

    # Run an API request for each of the cities
    try:
        city_weather = requests.get(city_url).json()
        # Parse out the latitude, longitude, max temp, humidity, cloudiness, wind, country, and weather description
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_weather_descrip = city_weather["weather"][0]["description"]
        city_country = city_weather["sys"]["country"]    
            
        # Append the city information into the city_data list
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Current Description":city_weather_descrip})
    
    # If an error is experienced, skip the city
    except:
        print("City not found. Skipping...")
        pass

# Indicate that the data retrieval is complete 
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | ribeira grande
Processing Record 2 of Set 1 | lebu
Processing Record 3 of Set 1 | sitka
Processing Record 4 of Set 1 | punta arenas
Processing Record 5 of Set 1 | gubkinskiy
Processing Record 6 of Set 1 | ushuaia
Processing Record 7 of Set 1 | taolanaro
City not found. Skipping...
Processing Record 8 of Set 1 | ponta do sol
Processing Record 9 of Set 1 | barrow
Processing Record 10 of Set 1 | iwaki
Processing Record 11 of Set 1 | hobart
Processing Record 12 of Set 1 | hithadhoo
Processing Record 13 of Set 1 | port hedland
Processing Record 14 of Set 1 | mezen
Processing Record 15 of Set 1 | luderitz
Processing Record 16 of Set 1 | vaitupu
City not found. Skipping...
Processing Record 17 of Set 1 | bonthe
Processing Record 18 of Set 1 | port augusta
Processing Record 19 of Set 1 | xiangfan
Processing Record 20 of Set 1 | atuona
Processing Record 21 of Set 1 | isangel
Processing Record 22 of Set 1 | port macquarie
Processing Record 23 of Set 1 | san lawrenz
Processing Record 24 of Set 1 | yellowknife
Processing Record 25 of Set 1 | dikson
Processing Record 26 of Set 1 | kapaa
Processing Record 27 of Set 1 | vostok
Processing Record 28 of Set 1 | rikitea
Processing Record 29 of Set 1 | grand river south east
City not found. Skipping...
Processing Record 30 of Set 1 | boksitogorsk
Processing Record 31 of Set 1 | campana
Processing Record 32 of Set 1 | busselton
Processing Record 33 of Set 1 | kulhudhuffushi
Processing Record 34 of Set 1 | upington
Processing Record 35 of Set 1 | pevek
Processing Record 36 of Set 1 | aktas
Processing Record 37 of Set 1 | bluff
Processing Record 38 of Set 1 | polovinnoye
Processing Record 39 of Set 1 | la ronge
Processing Record 40 of Set 1 | saskylakh
Processing Record 41 of Set 1 | mount isa
Processing Record 42 of Set 1 | norman wells
Processing Record 43 of Set 1 | shimoda
Processing Record 44 of Set 1 | camacha
Processing Record 45 of Set 1 | barentsburg
City not found. Skipping...
Processing Record 46 of Set 1 | kaitangata
Processing Record 47 of Set 1 | mataura
Processing Record 48 of Set 1 | husavik
Processing Record 49 of Set 1 | grindavik
Processing Record 50 of Set 1 | alofi

NameError: name 'time' is not defined

In [13]:
# Print the length of the city_data list to verify how many cities you have
len(city_data)

46

## Add the weather data to a new DataFrame.

In [14]:
# Use the city_data list to create a new pandas DataFrame.
city_data_df = pd.DataFrame(city_data)

In [15]:
# Display sample data
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
0,Ribeira Grande,38.5167,-28.7000,61.20,67,40,13.80,PT,scattered clouds
1,Lebu,-37.6167,-73.6500,58.78,70,52,12.93,CL,broken clouds
2,Sitka,57.0531,-135.3300,44.49,70,100,19.57,US,overcast clouds
3,Punta Arenas,-53.1500,-70.9167,57.31,51,20,8.05,CL,few clouds
4,Gubkinskiy,64.4340,76.5026,-5.84,87,72,16.55,RU,broken clouds
5,Ushuaia,-54.8000,-68.3000,58.66,33,0,5.75,AR,clear sky
6,Ponta Do Sol,32.6667,-17.1000,69.71,85,100,1.12,PT,overcast clouds
7,Barrow,71.2906,-156.7887,10.42,92,100,2.77,US,overcast clouds
8,Iwaki,37.0500,140.8833,59.68,90,9,8.48,JP,clear sky
9,Hobart,-42.8794,147.3294,52.27,75,75,0.00,AU,broken clouds

In [16]:
# Display the DataFrame's column names using the columns Pandas function
city_data_df.columns

Index(['City', 'Lat', 'Lng', 'Max Temp', 'Humidity', 'Cloudiness',
       'Wind Speed', 'Country', 'Current Description'],
      dtype='object')

In [17]:
# Create a list to reorder the column names as follows:
# "City", "Country", "Lat", "Lng", "Max Temp", "Humidity",  "Cloudiness", "Wind Speed",  "Current Description"
new_column_order= ["City","Country","Lat","Lng","Max Temp","Humidity","Cloudiness","Wind Speed","Current Description"]

# Recreate the DataFrame by using the new column order
city_data_df=city_data_df[new_column_order]

# Display sample data
city_data_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Ribeira Grande,PT,38.5167,-28.7000,61.20,67,40,13.80,scattered clouds
1,Lebu,CL,-37.6167,-73.6500,58.78,70,52,12.93,broken clouds
2,Sitka,US,57.0531,-135.3300,44.49,70,100,19.57,overcast clouds
3,Punta Arenas,CL,-53.1500,-70.9167,57.31,51,20,8.05,few clouds
4,Gubkinskiy,RU,64.4340,76.5026,-5.84,87,72,16.55,broken clouds
5,Ushuaia,AR,-54.8000,-68.3000,58.66,33,0,5.75,clear sky
6,Ponta Do Sol,PT,32.6667,-17.1000,69.71,85,100,1.12,overcast clouds
7,Barrow,US,71.2906,-156.7887,10.42,92,100,2.77,overcast clouds
8,Iwaki,JP,37.0500,140.8833,59.68,90,9,8.48,clear sky
9,Hobart,AU,-42.8794,147.3294,52.27,75,75,0.00,broken clouds
10,Hithadhoo,MV,-0.6000,73.0833,81.34,72,42,15.64,scattered clouds
11,Port Hedland,AU,-20.3167,118.5667,68.05,88,0,0.00,clear sky
12,Mezen,RU,65.8522,44.2400,32.79,97,100,9.35,overcast clouds
13,Luderitz,NA,-26.6481,15.1594,59.05,86,0,9.57,clear sky
14,Bonthe,SL,7.5264,-12.5050,79.09,80,8,5.44,clear sky
15,Port Augusta,AU,-32.5000,137.7667,63.97,69,69,7.29,broken clouds
16,Xiangfan,CN,32.0422,112.1448,53.10,64,100,8.05,overcast clouds
17,Atuona,PF,-9.8000,-139.0333,77.95,77,2,15.55,clear sky
18,Isangel,VU,-19.5500,169.2667,73.51,88,100,6.91,overcast clouds
19,Port Macquarie,AU,-31.4333,152.9167,67.89,94,100,8.05,overcast clouds
20,San Lawrenz,MT,36.0553,14.2040,62.85,92,100,10.65,overcast clouds
21,Yellowknife,CA,62.4560,-114.3525,16.32,100,100,5.75,light snow
22,Dikson,RU,73.5069,80.5464,-8.70,100,96,5.50,overcast clouds
23,Kapaa,US,22.0752,-159.3190,82.38,69,100,19.57,light rain
24,Vostok,RU,46.4856,135.8833,24.93,97,100,3.24,snow
25,Rikitea,PF,-23.1203,-134.9692,74.01,86,65,18.72,broken clouds
26,Boksitogorsk,RU,59.4740,33.8485,45.52,72,53,16.58,broken clouds
27,Campana,AR,-34.1687,-58.9591,80.24,86,100,7.25,overcast clouds
28,Busselton,AU,-33.6500,115.3333,53.33,75,79,10.92,broken clouds
29,Kulhudhuffushi,MV,6.6221,73.0700,81.16,73,73,6.60,broken clouds
30,Upington,ZA,-28.4478,21.2561,73.78,21,0,14.97,clear sky
31,Pevek,RU,69.7008,170.3133,-0.92,97,100,5.44,light snow
32,Aktas,KZ,49.7789,72.9608,26.35,94,100,22.68,overcast clouds
33,Bluff,NZ,-46.6000,168.3333,52.23,90,100,7.74,overcast clouds
34,Polovinnoye,RU,54.7914,65.9864,33.73,98,100,15.23,light snow
35,La Ronge,CA,55.1001,-105.2842,17.82,67,75,13.80,broken clouds
36,Saskylakh,RU,71.9167,114.0833,-17.86,99,99,6.02,overcast clouds
37,Mount Isa,AU,-20.7333,139.5000,74.97,83,61,5.75,broken clouds
38,Norman Wells,CA,65.2820,-126.8329,12.24,92,75,0.00,broken clouds
39,Shimoda,JP,34.6667,138.9500,60.10,78,44,9.26,scattered clouds
40,Camacha,PT,33.0833,-16.3333,65.62,77,20,4.61,few clouds
41,Kaitangata,NZ,-46.2817,169.8464,59.81,49,86,3.18,overcast clouds
42,Mataura,NZ,-46.1927,168.8643,56.64,63,95,5.97,light rain
43,Husavik,IS,66.0449,-17.3389,36.81,79,85,8.28,overcast clouds
44,Grindavik,IS,63.8424,-22.4338,40.95,93,40,10.36,scattered clouds
45,Alofi,NU,-19.0595,-169.9187,80.49,69,40,14.97,scattered clouds

In [13]:
# Display the data types of each column by using the dtypes Pandas function
# YOUR CODE HERE

City                    object
Country                 object
Lat                    float64
Lng                    float64
Max Temp               float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Current Description     object
dtype: object

## Export the DataFrame as a CSV file, and save it as `WeatherPy_Database.csv` in the `Weather_Database` folder.

In [18]:
# Set the output file name
output_data_file = "WeatherPy_Database.csv"

# Export the city_data DataFrame into a CSV file
city_data_df.to_csv(output_data_file, index_label="City_ID")